locals {
  name_prefix = "demo-${var.environment}"
  is_prod     = var.environment == "prod"
  replicas    = local.is_prod ? max(var.replicas, 3) : var.replicas
  common_tags = merge(var.tags, {
    environment = var.environment
    managed_by  = "terraform"
  })
  out_dir = "${path.module}/out/${var.environment}"
}

resource "local_file" "app_conf" {
  filename = "${local.out_dir}/app.conf"
  content  = <<-EOT
    # ${local.name_prefix} — generated by Terraform, do not edit
    environment = ${var.environment}
    port        = ${var.app_port}
    log_level   = ${var.log_level}
    replicas    = ${local.replicas}
    ${join("\n", [for key, value in local.common_tags : "tag.${key} = ${value}"])}
  EOT
}

resource "local_sensitive_file" "db_env" {
  filename        = "${local.out_dir}/db.env"
  file_permission = "0600"
  content         = "DB_PASSWORD=${var.db_password}\n"
}
