locals {
  full_name = "${var.name}-${var.environment}"
  app_dir   = "${var.out_dir}/${local.full_name}"
  ports     = [for i in range(var.replicas) : var.port + i]
}

resource "local_file" "config" {
  filename = "${local.app_dir}/app.conf"
  content  = <<-EOT
    name        = ${var.name}
    environment = ${var.environment}
    ports       = ${join(",", local.ports)}
  EOT
}

resource "local_file" "nginx_site" {
  filename = "${local.app_dir}/site.conf"
  content  = <<-EOT
    upstream ${local.full_name} {
    ${join("\n", [for p in local.ports : "    server 127.0.0.1:${p};"])}
    }
    server {
        listen 80;
        server_name ${var.name}.${var.environment}.localtest.me;
        location / { proxy_pass http://${local.full_name}; }
    }
  EOT
}

resource "local_file" "readme" {
  filename = "${local.app_dir}/README.md"
  content  = "# ${local.full_name}\n\nGenerated by the webapp Terraform module. Do not edit.\n"
}
